version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: scanny_database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bazepodataka
      POSTGRES_DB: scanny
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: